server:
  port: 8082

spring:
  application:
    name: notification-service
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://config-server:8888}
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}

notification:
  kafka:
    topic: notification-events
