server:
  port: 8083

spring:
  application:
    name: rag-service
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://config-server:8888}
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
