server:
  port: 8084

spring:
  application:
    name: tool-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
  config:
    import: optional:configserver:http://localhost:8888
