server:
  port: 8084

spring:
  application:
    name: tool-service
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://config-server:8888}
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
